title: Mandela efekt
baseURL: https://happyradka.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: "Domovsk√° strana"
      url: /
      weight: 10
    - name: "Novinky"
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

